name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send photo message
        uses: appleboy/telegram-action@master
        with:
            to: 1045217218
            token: 6952315780:AAH28VxKmYp3xZQ6DcKUcqKQfSiTOzIqMLE
            message: send photo message
            photo: tests.github.png
            document: tests.gophercolor.png
