# This is a basic workflow to help you get started with Actions

name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: 1045217218
          token: 6952315780:AAH28VxKmYp3xZQ6DcKUcqKQfSiTOzIqMLE



          
          message: send photo message
    photo: tests/github.png
    document: tests/gophercolor.png

