
name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: 1045217218
          token: 6952315780:AAH28VxKmYp3xZQ6DcKUcqKQfSiTOzIqMLE
          message: Ley
          photo: GameJump/photo.jpg
        
